server:
  port: 8083

spring: 
  application:
    name: ApiGateway

  cloud:
    gateway:
      routes:
      - id: DEPARTMENT
        uri: lb://DEPARTMENT
        predicates:
        - path=/department/**
        
      - id: STUDENT
        uri: lb://STUDENT
        predicates:
        - path=/student/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance: 
    hostname: localhost